-- Drop tables:
DROP TABLE IF EXISTS tickets;
DROP TABLE IF EXISTS ratings;
DROP TABLE IF EXISTS movie_session;
DROP TABLE IF EXISTS session;
DROP TABLE IF EXISTS theatre;
DROP TABLE IF EXISTS movie_predecessors;
DROP TABLE IF EXISTS movie_genres;
DROP TABLE IF EXISTS movies;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS subscribes;
DROP TABLE IF EXISTS agreement;
DROP TABLE IF EXISTS rating_platforms;
DROP TABLE IF EXISTS audience;
DROP TABLE IF EXISTS directors;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS database_managers;
